### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by MrFibunacci** [FramyFramework/Framy#37]
# Introduction
We use klein.php eversince, but since I want some changes we will edit it massively. Klein.php has manny own implementations of dependency injections, collections, and validation. We will replace these things with our own stuff and implement klein.php deeper into the framework.

# Todo
- [x] Rename Rout component to Routing
- [x] Move code from klein dir to root inside the comp. 
- [x] Implement Validation component and StdValidateTrait instead of klein.php validation
- [ ] Implement StdArrayObject in the collections

**Comment by MrFibunacci** [comment]
> Implement StdArrayObject in the collections
not really needed so we can do this later
